name: hostel_mess_app
description: A new Flutter project for a hostel mess.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_staggered_animations: ^1.1.1
  intl: ^0.19.0
  google_nav_bar: ^5.0.6  # For the modern navigation bar
  google_fonts: ^6.1.0    # For beautiful fonts
  # The problematic packages have been removed.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true