name: Hostel
description: A new Flutter project for a hostel mess.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UTILITY PACKAGES
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  url_launcher: ^6.2.6
  path_provider: ^2.1.3
  
  # UI & ANIMATION PACKAGES
  flutter_staggered_animations: ^1.1.1
  google_nav_bar: ^5.0.6
  google_fonts: ^6.1.0
  lottie: ^3.1.2
  liquid_pull_to_refresh: ^3.0.1
  animated_bottom_navigation_bar: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets section to include your Lottie files and icon
  assets:
    - assets/
  
# CORRECT: This is now a top-level key, at the root of the file.
flutter_icons:
  android: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "transparent"
